$commonscript = <<-SCRIPT
sudo yum install epel-release -y
sudo echo "LANG=en_US.utf-8" > /etc/environment
sudo echo "LC_ALL=en_US.utf-8" >> /etc/environment
sudo yum install wget -y
sudo wget -O /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker-ce -y 
sudo service docker start
sudo chkconfig docker on 
sudo usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
    # Box
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    end


    config.vm.provision "shell", inline: $commonscript
end
